config/routes.rb
Rails.application.routes.draw do
  resources :users do
    post 'register', :on => :collection
    post 'login', :on => :collection
  end
  
  root 'users#new'
  
  resources :messages do 
    post 'random', :on => :collection
  end
  
  
   get "stuff" => "trains#stuff", :defaults => { :format => 'json' }
   get 'trains' => 'trains#index'
   get 'trains_another' => 'trains#another'
   
   get 'clockwork' => 'trains#clockwork'

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/text_queue.rb
class TextQueue < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :from, :message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  def random
    @time = (Time.now - (10*60)).strftime("%H:%M")
    if params[:content] && params[:phone]
      @user = User.where.not(phone: params[:phone]).order("RANDOM()").first
        if HTTParty.post("https://api.clockworksms.com/http/send.aspx", {query: {
             :key => "3cf1f7012e1ad38c8b0d36a32f18fc40673f7199", 
             :to => "#{@user.phone}",
             :from => "#{params[:phone]}",
             :content => "#{params[:content]}"}})
        render status: 200
      else
        render status: 400
      end
    else
      render status: 400 , json: "Invalid params".to_json
    end
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:name)
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  def index
    
  end
  
  def stuff
    @stuff =  TextQueue.all
    

    respond_to do |format|
      format.json { render :json => @stuff.to_json }
    end
  end
  
  def clockwork
    system ('rake clockwork')
    flash[:notice] = "sent some asshole a text"
    redirect_to action: "index"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

  end
  
  def setup
    @user = User.new
  end
  
  def unsubcribe
  
  end
  
  # GET /users/1
  # GET /users/1.json
  def show
  end

  def register
    @time = (Time.now - (600)).strftime("%H:%M")
    if params[:user_name] && params[:password]
      if User.create(phone: params[:user_name], password: params[:password])
        HTTParty.post("https://api.clockworksms.com/http/send.aspx", {query: {
             :key => "3cf1f7012e1ad38c8b0d36a32f18fc40673f7199", 
             :to => "#{params[:user_name]}", 
             :content => "The Time ten minutes ago was #{@time}"}})
        render status: 200
      else
        render status: 400
      end
    else
      render status: 400 , json: "Invalid params".to_json
    end
  end
  
  def login
    if params[:user_name] && params[:password]
      if User.find_by_phone_and_password(params[:user_name], params[:password])
        render status: 200
      else
        render status: 404
      end
    else
      render status: 400 , json: "Invalid params".to_json
    end
  end
    

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    
    if params[:commit] == "message" && params[:user][:from] && params[:user][:message]
        @user3 = User.order("RANDOM()").first
        HTTParty.post("https://api.clockworksms.com/http/send.aspx", {query: {
               :key => "3cf1f7012e1ad38c8b0d36a32f18fc40673f7199", 
               :to => "#{@user3.phone}",
               :from => "#{params[:user][:from]}",
               :content => "#{params[:user][:message]}"}})
       respond_to do |format|
         format.html { redirect_to action: :new, notice: 'User was successfully texted.' }
         format.json { head :no_content }
       end    
    end
    
  if params[:commit] == "delete" && params[:user][:phone] && params[:user][:password]
    @user2 = User.find_by_phone_and_password(params[:user][:phone], params[:user][:password])
    if @user2 && @user2.destroy
        respond_to do |format|
          format.html { redirect_to action: :new, notice: 'User was successfully destroyed.' }
          format.json { head :no_content }
        end
    else
      respond_to do |format|
        format.html { redirect_to action: :new, notice: 'you do not exist' }
        format.json { head :no_content }
      end
    end
  end
  
  if params[:commit] == "save" && params[:user][:phone]   
    if @user.save
      @time = (Time.now - (600)).strftime("%H:%M")
      HTTParty.post("https://api.clockworksms.com/http/send.aspx", {query: {
           :key => "3cf1f7012e1ad38c8b0d36a32f18fc40673f7199", 
           :to => "#{@user.phone}", 
           :from => "Rasputin",
           :content => "The Time ten minutes ago was #{@time}"}})
      respond_to do |format|
        format.html { redirect_to action: :new, notice: 'User was successfully created.' }
        format.json { render :new, status: :created, location: @user }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
   end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :content %><br>
    <%= f.text_area :content %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.name %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @message.name %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/trains/index.html.erb
<%= link_to "Send Text", clockwork_path, :class => "btn btn-default" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<html>
    <head>
        <title>The Rasputin Impersonators</title>

        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <style>
            body {
                padding-top: 50px;
                font-size: 20px;
            }
            input[type="text"] {
                padding: 10px;
            }
            div.row {
                margin-top: 20px;
            }
        </style>

    </head>
    <body>

      <%= form_for(@user) do |f| %>
        <div class="container">
            <div class="row" style="margin-top: 50px">
                <div class="col-sm-4 col-sm-offset-1">
                    <div class="text-center" style="margin-bottom: 100px">
                        <h1>Totally Useless Information Service</h1>
                    </div>

                      <% if @user.errors.any? %>
                        <div id="error_explanation">
                          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

                          <ul>
                          <% @user.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                          </ul>
                        </div>
                      <% end %>

                      <div class="row">
                          <div class="col-sm-12">
                              <%= f.text_field :phone, placeholder: "Phone Number", style: "width: 100%" %>
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-sm-12">
                              <%= f.text_field :password, placeholder: "Password", style: "width: 100%" %>
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-sm-6">
                              <button class="btn btn-lg btn-primary" style="width: 100%" name="commit" value="save" type="submit">Subscribe</button>
                          </div>
                          <div class="col-sm-6">
                              <button class="btn btn-lg btn-primary" style="width: 100%" name="commit" value="delete" type="submit">Unsubscribe</button>
                          </div>
                      </div>
                </div>
                <div class="col-sm-1" style="border-right: 3px solid #999; height: 400px;"></div>
                <div class="col-sm-4 col-sm-offset-1">
                    <div class="text-center" style="margin-bottom: 20px">
                        <h1>Send Text to Random Number</h1>
                    </div>
                    <div class="row">
                      <div class="col-sm-12">
                          <%= f.text_field :from, placeholder: "From Phone Number", style: "width: 100%" %>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-12">
                          <%= f.text_area :message, placeholder: "Your text here ...", style: "width: 100%; height: 130px;" %>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-12">
                        <button class="btn btn-lg btn-primary" style="width: 100%" name="commit" value="message" type="submit">Send Message</button>
                      </div>
                    </div>
                </div>
            </div>
        </div>
                    <% end %>
    </body>
</html>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>